### ISSUE TITLE
Display "last commit" date for each package

### ISSUE THREAD

**Issue by bluechi** [frictionlessdata/frictionlessdata.io#175]
Originally posted here
https://github.com/datasets/registry/issues/82

It would be helpful if the "last commit" date was displayed somewhere on the package view page and/or the main "Find Data Packages" page so that users can see when this package was last updated. Maybe even sort the packages according to the most recent commit.

**Comment by rgrp** [comment]
This issue was moved to okfn/data.okfn.org-new#3
