### ISSUE TITLE
[v2] Theme: Final Fixes miscellany

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/frictionlessdata.io#425]
Final fixes for the theme, see #402.

Steps:

* [x] Review main issue and extract remaining items https://github.com/frictionlessdata/project/issues/402
* [x] Anything else e.g. stuff above in actions (move that here)
* [x] Prioritize and/or categorize tasks (e.g. by page)

## Acceptance

* [x] Home page ready to go
* [x] Team page ready to go
* [x] Base theme ready to go
  * [x] Footer
  * [x] Navbar

### Base theme

* [x] add jobs to be done to the navigation bar (+ team(?))
* [x] Ensure there are no links to HTML pages in navbar
  * /about/, not /about.html
* ~~Tweak the logo (with text and thicker f)~~ moved to #428 
* [x] mock footer
* [x] Finish frontmatter spec
* [x] (??) fix hexagon width and general look on e.g. the jobs pages e.g. http://next.frictionlessdata.io/jobs/document-dataset/

### Home page

* [x] Redo main hero image as still not very strong
* [x] Tweak icons for the front page 
* [x] Implement new mockup

### Team

* [x] little bugs on the team page e.g. spacing and double `<hr>` (as it looks weird after we added the default vuepress styles to the theme)

### Someday maybe 

* ~~Have markdown in html e.g. front page code samples - see vuejs/vuepress#257~~
* [x] BLOG show the tags on the blog index page

**Comment by monikappv** [comment]
I tried to tweak the logo twice 1. using adobe XD 2. using inkscape - made just the F thicker, haven't 
changed the font next to the blue form, and saved it as svg file (at that point it looked pretty good, see below):

![logo-tweaked](https://user-images.githubusercontent.com/56799741/75053272-a4ef3d00-54d9-11ea-816e-1c4f7e265233.png)

When I tried to implement it on the website, it seems like the font next to the dot has also changed and looks also thicker and uglier, as shown below:

![logoUgly](https://user-images.githubusercontent.com/56799741/75052983-2f836c80-54d9-11ea-8f31-ce52bc30902f.png)

this is the original version before implementing the changes:

![logoBeautiful](https://user-images.githubusercontent.com/56799741/75052790-d287b680-54d8-11ea-82d5-d6ae0f470fb0.png)

**Comment by rufuspollock** [comment]
FIXED. Everything done (for some time) and moved one last item (logo tweak) out to #428.
