### ISSUE TITLE
fd.io Team Page organisation

### ISSUE THREAD

**Issue by jobarratt** [frictionlessdata/frictionlessdata.io#436]
# Overview

Suggested approach for how to organise the Team page on the new frictionless data site. 
https://next.frictionlessdata.io/team/#active-core-team-members

---

- Can we remove 'core' from the first heading heading? I feel 'active team members' or just 'team members' is fine. 
- is it possible to have a grid arrangement, so there is not the inevitable sense of hierarchy that comes with a list
- Suggestion that 'Core Team Emeritis' is not useful and we should remove this section entirely. 

- Community Partners' becomes a place to populate with Tool Fund partners, Frictionless Data Fellows or others who are explicitly working on the project. the 'core focus' can indicate what specifically they are working on. 

- Suggestion that we should add an area for highlighting organisations. So we have a simple system of logo, name and link. This way we can feature pilots partners (we link to a blog post within the site) or other 'partners' working on FD. i.e Data Curator etc. Open question as to whether we add this here or elsewhere. Should consider this with in conjunction with thinking about the list of partners on the home page. 

Please preserve this line to notify @lwinfree (lead of this repository)

**Comment by rufuspollock** [comment]
@jobarratt what's the issue with core - i took it from vuejs and reflects that these people are often "core". What's your concern there? (I'm not attached to the name but indicating some sense of this can be useful so want to understand if its about the name or something else).

@jobarratt i've got no issues with hierarchy 😉 - if that is a concern there i'm happy to have a chat as that is much more fundamental thing 😉 (and let's distinguish growth hierarchies from dominator hierarchies). Re UX itself: Layout again was inspired by excellent vuejs ...  We can do grids but i don't think are so great UX actually.

@jobarratt core team emeritus was inspired again by vuejs. Wondered what's the issue with this - we just wanted to acknowledge people who've contributed before but maybe now no longer. Happy to remove wonder if you think there is another way to achieve this.

Community partners: 👍 sounds great. Do you want to go for a pull request for that.

Organizations: 👍 👍

**Comment by jobarratt** [comment]
Running through his is an assumption that vuejs is excellent! i don't share this view, at least for this particular issue. I'm commenting on the design as i see it on it's own terms. 

I mean i do have an issue with hierarchy actually. In terms of dominator/growth i think this depends on the perspective on the viewer rather than what we think, and that's what i'm talking about here - it's a UX consideration. What's your UX issues with grids? It would also be a way to get information on the page more efficiently. This theme is rather wasteful of space.

In terms of Core i don't mind that much. 'Core Team' is better for me than 'Active Core Team' which sounds to me like a CrossFit squad. It just seems excessive and doesn't add much. And whereas i accept that valuable inspiration has come from vuejs, i don't think we need to just lift without considering what it's important for us to communicate, or not communicate. 

I will do a pull request for community partners

and perhaps we can discuss an approach to orgs next week. would be interested in others opinions on this point @lwinfree @Irio @monikappv

**Comment by rufuspollock** [comment]
@jobarratt how are you getting on with your PR for community partners?

Also are you happy for us to have some emeritus people e.g. Dan?

**Comment by jobarratt** [comment]
@rufuspollock from my site this is done. 

I'm not keen on emeritus, though if you feel strongly please reach out to relevant people. i do want to insist on explicit consent for Emeritus, and if we have that then fine to have a section for it. I've removed for now. 

I'm going to ask @lwinfree to review my PR and add a couple of details and then we can merge.

**Comment by rufuspollock** [comment]
@jobarratt let's remove emeritus for now, np. We can re-add later if it becomes useful.

**Comment by lwinfree** [comment]
closed via https://github.com/frictionlessdata/website-v2/pull/46

**Comment by lwinfree** [comment]
hmmm the PR passed tests on github, but has now failed to build. @lauragift21 can you help me look at this? or is there someone else that is the point person here? https://github.com/frictionlessdata/website-v2/runs/511553111?check_suite_focus=true thanks!

**Comment by lauragift21** [comment]
Of cos @lwinfree I'll have a look.

**Comment by lauragift21** [comment]
I fixed it here and fixed a broken image https://github.com/frictionlessdata/website-v2/pull/48 @lwinfree

**Comment by rufuspollock** [comment]
FIXED. @lauragift21 fixed it i believe.

@lauragift21 please close these when you complete them 😉
