### ISSUE TITLE
Post blog about Fosdem talk with slides / content

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/frictionlessdata.io#437]
@lwinfree awesome we did a talk at Fosdem and let's blog about it 😄

Would you be up for putting up a post with a summary and any slides / content / photos you have?

**Comment by lwinfree** [comment]
slides: http://bit.ly/FDfosdem

**Comment by lwinfree** [comment]
and here's the rest of the info including a video of the talk: https://fosdem.org/2020/schedule/event/open_research_frictionless_data/

**Comment by rufuspollock** [comment]
@lwinfree great - are you updating for blogging this on FD?

**Comment by lwinfree** [comment]
I've been thinking about this & think it will actually make a better tweet than blog post. I can tweet about it on Thursday as a #tbt post too. I think more people will see it this way too

**Comment by lwinfree** [comment]
Hey @rufuspollock the links to the slides & to the video are in the comments above 👆

**Comment by sglavoie** [comment]
**WONTFIX**: Closing because @lwinfree wrote in [this comment](https://github.com/frictionlessdata/project/issues/437#issuecomment-623641415) she is taking care of this on Twitter. No further action needed.
