### ISSUE TITLE
Brainstorm list of howtos (maybe in job story form)

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/frictionlessdata.io#438]
Create a list (e.g. 5-20) potential howtos we could write re FD. Preferred form would be a job story. Example:

> When I have a data package I want to import it into pandas as a data frame so that I can analyze in pandas my favourite tool

**IN PROGRESS in this spreadsheet: https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit#gid=1272791416**

@lwinfree @roll I've booted this issue for you guys following on from chat the other day. Feel free to amend / update.

## Acceptance

* [x] A list in spreadsheet or e.g. here or hackmd of 5-20 potential howtos
  * if we can, add example of someone who had this
  * Bonus: value + cost estimates

## Tasks

* [x] Brainstorm the list
* [x] Review ...

**Comment by lwinfree** [comment]
Hey @rufuspollock, thanks for getting this started. We can document our work in this issue. However, I also want to note that we had all agreed that I was going to do this task (start this issue), and I just want to make sure that we are all still on the same page and sticking to our project plan 😃

**Comment by rufuspollock** [comment]
@lwinfree yes, you are doing the issue. I just booted just b/c i had not seen anything in last 48h and did not want it to overflow from (my) stack.

**Comment by lwinfree** [comment]
I think this brings up a good point that it would be helpful to put project management guidelines on the agenda for the next call. I want to make sure that we all have the same expectations and agree to a plan of action to optimally work together. I'm starting the list in the existing spreadsheet [here](https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit#gid=1272791416) & then Evgeny & I will go from there!

**Comment by roll** [comment]
I think we can use some generalized approach for integration specific tutorials. We have a matrix of source/targets and actions/stories:

## Source/target

- SQL
- BigQuery
- Pandas
- ElasticSearch
- SPSS
- CKAN
- [ extend here ]

## Stories

- Export data and metadata from {source} to FD
- Import data and metadata from FD to {target}
- [ extend here ]

Writing or adopting a first tutorial could cost a day or so but generating the next 11 will be much faster.

PS.
I agree that having live code examples like using `repl.it` is must-have for the tutorials.

**Comment by rufuspollock** [comment]
FIXED. We now have a list of 10 howtos. We will keep adding no doubt but done for now. Will be follow up issues to actually do howtos.
