### ISSUE TITLE
[inbox] Rufus Inbox re Frictionless

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/frictionlessdata.io#450]
Inbox is GTD inbox of things in backlog that we may want to process.

## Inbox

* [ ] 🐘 product page for `data` tool
  * [ ] design for `data` tool (always bet on javascript)
* [ ] Change logo on github.com/frictionless to new logo ~5m
* [ ] favicon for the sites either based on logo or package 📦 or toolbox 🧰 
* [ ] Merge command line zen into zen of data … (and move this to datahub.io/zen ?) https://github.com/rufuspollock/command-line-zen
* [ ] Look up frictionless components diagram from old data.okfn.org
* [ ] Finish frictionless data specs overview diagram - https://docs.google.com/drawings/d/14IrVuPcACNMbf48E95C6u7jSAe8EqBGhicBpvQK8SHA/edit
* [ ] Register frictionlessdata on instagram
* [ ] Map of the specifications and how they fit together frictionlessdata/specs#780 
* [ ] Question / Pattern list - cf field guide and see https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit#gid=574770435
* [ ] Write up various mental models for data work in a blog post - source for these in appendix of Design doc https://docs.google.com/document/d/1Dg6KWFPcY2hCs3KfCQi8LhATr96EvGJTtkCXd_Fax6Q/edit#heading=h.1k0499yvh69y
* [ ] About page
  * [ ] Info about who's behind it
  * [ ] A bit of history
  * [ ] Project vision

## Misc Look / UX

* [ ] 2020-05-21 events page should not have sidebar. Title is frictionless events (not frictionless data).

## Naming

* [x] Work out Naming: Specs vs Patterns vs ... **going with patterns for now and specs where mentioned are formal implementations of those patterns**
* [ ] framework vs toolkit (for tagline too) **toolkit**

## Theming

* [ ] Warning, tip boxes etc like vuejs.org (also maybe change tip to info so like hackmd ...?)

## Front page

* [ ] "Built by leaders in the data space with combined decades of experience building data platforms and tools"
* [ ] (?) Add data journalists to list of folks frictionless data is relevant for ... (on front page?)
* [ ] terminal animation to illustrate some of our tools - e.g. using https://github.com/mattboldt/typed.js/ (example is jrnl.sh)

## People to contact

* [ ] Contact simon willison @simonw for a chat re frictionless data and datassette and data tools in general  😄 https://simonwillison.net/

## Future

* Markdown-it plugin for csv so that we can have csv and have it rendered (perfect would be a switcher to show "raw" csv and a nice table) - see https://github.com/frictionlessdata/forum/issues/8 
* Markdown-it plugin for data resource ... (where data comes after ...) - see https://github.com/frictionlessdata/forum/issues/7

### 2020-02-23 - whilst working on guide

Data Patterns

Core: What is "data"?

The "atomic" metaphor: an atom as a single value, assembled into molecules, then macromolecules etc.

* A value
* Fields and Records (Columns and Tables)
* RecordSets and Datasets (Tables and Spreadsheets/Databases/Datasets)

Flows: doing stuff with data?

Core pattern: a pipeline of operations (on data)

**Comment by simonw** [comment]
Let's talk! DM me on Twitter - https://twitter.com/simonw
