### ISSUE TITLE
[idea] Deprecate software issue tracker and merge issues with project tracker

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/frictionlessdata.io#467]
@roll what do you think of merging the issues here with project tracker and deprecating / deleting this repo?

Why?

* One way to do things is preferable: right now not clear what is here vs project e.g. https://github.com/frictionlessdata/project/issues/380 - should this be here or in project?
* We don't have the volume of issues or the subdivision of teams that would warrant having a separate system

**Comment by roll** [comment]
Hi @rufuspollock, @lwinfree 

It's done. Also moved to here a few additional issues that were lost on other inactive issues trackers (from the repos under the project section - https://github.com/frictionlessdata/docs/blob/master/TEAMS.md)

I think when the active stage of the site update is finished it makes sense also to merge the website issues tracker into this one (project). It will make the only one entry point for all non-tech issues.

**Comment by roll** [comment]
BTW I'm not sure I fully understand the difference between this issues tracker and `forum` (a lot of issues/discussions are interchangeable in my eyes)

**Comment by rufuspollock** [comment]
@roll i hear you re forum and project so to clarify: forum i hope is a welcoming place where people can open a first issue, have a look around etc.

If those issues are substantive they may move elsewhere ... (e.g. i did that with a spec issue recently). But it's a good landing spot.

Summary:

* Forum: the default place for anyone out there to open an issue. It means *one* place.
  * Also the catch-all for general questions, suggestions, ideas, support requests etc.
* Project: the default place for core team to organize and plan work, schedule sprints etc. NOT for general discussion, ideas, support etc.

**Comment by roll** [comment]
I've moved a few general discussions like issues from the lib trackers to the forum. Using criteria something like `is it too broad and clearly not actionable atm -> forum`

**Comment by rufuspollock** [comment]
@roll that's great - i've seen a bunch of them and it's been really useful.
