### ISSUE TITLE
page #s incorrect on blog

### ISSUE THREAD

**Issue by lwinfree** [frictionlessdata/frictionlessdata.io#480]
Hi! The page numbers for the blog are incorrect. Page 2 says page 1 on the page. Also the number on the page is different from the number in the URL pattern (see pic):
<img width="825" alt="blog page numbers" src="https://user-images.githubusercontent.com/17657625/79508173-9ff0ca80-7ffe-11ea-80a2-1b68e44983bc.png">

**Comment by roll** [comment]
Hi @lauragift21 

I've moved to the project tracker because it seems to have been forgotten because it's not a part to the project kanban board - https://github.com/frictionlessdata/project/projects/3

**Comment by roll** [comment]
I can confirm this issue still exists. Please take a look if you can

**Comment by lauragift21** [comment]
Yes, thanks @roll I didn't forget it. I will work on a fix.
