### ISSUE TITLE
The specs logo is outdated

### ISSUE THREAD

**Issue by roll** [frictionlessdata/frictionlessdata.io#481]
# Overview

It's still the blue one - https://specs.frictionlessdata.io/

---

Please preserve this line to notify @lwinfree (lead of this repository)

**Comment by rufuspollock** [comment]
@roll good point - these should link to a common url on frictionlessdata.io so if we update in one place it updates everywhere.

**Comment by rufuspollock** [comment]
@sglavoie do you think you could look at fixing this by linking to https://frictionlessdata.io/img/frictionless-color-full-logo.svg

**Comment by sglavoie** [comment]
@rufuspollock done! I've sent this PR: https://github.com/frictionlessdata/specs/pull/729
