### ISSUE TITLE
reproducible research page is missing

### ISSUE THREAD

**Issue by lwinfree** [frictionlessdata/frictionlessdata.io#482]
https://frictionlessdata.io/reproducible-research/

**Comment by lauragift21** [comment]
Yeah, It's linked in the footer. But I can also add it to the navbar. @lwinfree

**Comment by roll** [comment]
Sorry @lwinfree I didn't get that the link is missing (not the page itself)

**Comment by roll** [comment]
@lwinfree @lauragift21 
What do you think of having a section on the front page (colored horizontal stripe) like `What's happening in FD now / most important news`. For now, we kinda lack an ability to announce something etc.

Currently this section could contain e.g:
- Reproducible research (current Sloan grant project)
- We're looking for fellows
- OKFN/Datopian decided to join they forces

**Comment by roll** [comment]
@lauragift21 
I've re-opened for now because TBH this long `Reproducible Research` link in the header doesn't look perfect and easy to understand what is it. I've added an alternative idea in the prev comment

Please close @lwinfree @lauragift21 if you think if currently, it's fine

**Comment by lwinfree** [comment]
Hmm yeah I see what you mean @roll about ```Reproducible Research``` looking long in the navbar. What if it is linked on the ```Case Studies``` page? We also have ```Pilots``` that would be good to be linked on the ```Case Studies``` page too. What do you think @lauragift21? Does something like that make sense to you?

**Comment by lauragift21** [comment]
I agree. We shouldn't have so many items on the navbar as we do now.  About the `case-studies` page that is just `tags/case-studies` that list out all blog posts with that tag. I'm not sure how adding a link on the page will look like.

My suggestion is having a dropdown with `case-studies`, `pilots` and `reproducible research` links just like how we have `specs` and `help`  @lwinfree

**Comment by lwinfree** [comment]
@lauragift21 Yeah I like that idea! I think that would look nice.

**Comment by lauragift21** [comment]
Great! Can you suggest a name for that section that would make sense for the group?

**Comment by lwinfree** [comment]
@lauragift21 Maybe ```Use Cases```?

**Comment by lauragift21** [comment]
Yeah, I think that works. @roll what do you think?

**Comment by lauragift21** [comment]
FIXED. I've added the use cases tab to the website.

**Comment by lwinfree** [comment]
Thank you! This looks really nice :-)
