### ISSUE TITLE
How not to miss project-related issues/PRs posted on different issue trackers?

### ISSUE THREAD

**Issue by roll** [frictionlessdata/frictionlessdata.io#483]
We have around a dozen project-related (not software) issues tracker like `website`, `fellows`, `examples`, `notebooks` etc. Even having the line in an issue template like `please preserve @xxx to notify` doesn't always work because sometimes people delete it. Also, it goes out of the scope of this project https://github.com/frictionlessdata/project/projects/3 anyway

## Ideas

- [ ] Move this project - https://github.com/frictionlessdata/project/projects/3 - to organization level so all these issue trackers can be connected **WONTFIX. For now we can just converge on this issue tracker here and live with a project here as we need it ~rufus**
- [ ] Close these issue trackers and add there a link pointing at the `project` issues tracker (to repo description/readme/pinned issues) **YES to closing `fellows`, `examples` `website` `notebooks`**
- [ ] Update github issue/PR templates to automatically assign the lead of the repository (I didn't this in the first place because it wasn't supported for PRs but maybe it's fixed now). The lead will process the issue (read/answer/add labels) and de-assign if it's for backlog (or maybe transfer to `project`) **IMO i don't think this is necessary and i'm not sure how to do this - leads could just watch the repo and handle as needed ~rufus**

**Comment by lauragift21** [comment]
My thoughts on this - I think having all the project-related issues in one place is a nice idea. That way we are less likely to miss an issue and using an appropriate label to signify which project it belongs to will be helpful. @roll

**Comment by rufuspollock** [comment]
@roll can you help me get the job story here - i think it may be something like "When managing X i want to be notified of y so that Z" or "When managing FD I want to have an overview of work on issues so that XX"

That will allow me to comment better on the exactly proposals you have.

Aside:

> please preserve @xxx to notify

People should just *watch* repos - that's what the functionality is for IMO.

**Comment by roll** [comment]
> "When managing X I want to be notified of y so that Z" or "When managing FD I want to have an overview of work on issues so that XX"
It sounds good (esp #2)

Actually, I just wanted to flag that some issues (including kind important profiles discussions) were hidden almost from everyone because there are a lot of issue trackers. My idea was that we can do some consolidation as we did with the `software` one. But it's kind minor.

PS.
Regarding watching, I think a responsible for the repo person (lead) should set up the way that works for him/her.

**Comment by rufuspollock** [comment]
> Actually, I just wanted to flag that some issues (including kind important profiles discussions) were hidden almost from everyone because there are a lot of issue trackers. My idea was that we can do some consolidation as we did with the software one. But it's kind minor.

@roll I certainly think we can centralize most substantive issue stuff here in this repo for now in keeping with our simplicity and "one way to do things". Of course minor issues that  are very specific to that item can remain e.g. for notebooks or website. So overall, yes, let's consolidate here, and let's do that at issue tracker level rather than via boards.

**Comment by rufuspollock** [comment]
FIXED. AGREED that we consolidate on this repo for now. I've also updated description with comments on the ideas there.

@roll feel free to re-open if you feel i've missed something.
