### ISSUE TITLE
Institutionalize the fact that FD Github organization is software hub available for independent developers to have project on without loosing control/ownership? 

### ISSUE THREAD

**Issue by roll** [frictionlessdata/frictionlessdata.io#485]
I think we already have some projects that were created by independent developers and moved to the FD org. De facto we treat this project as independent (the core team doesn't have the power to make decisions there) but de jure this agreement doesn't exist yet anywhere neither as some kind of license nor even as a document/disclaimer. 

Currently, it's very actual because of the `dataflows` situation (as far as I understand the situation).

@lwinfree @akariv @rufuspollock WDYT? Does it make sense to think in this direction? If yes, what can we do (licenses/public agreement/etc)?

**Comment by rufuspollock** [comment]
@roll can you clarify a bit more. I think a given project under FD can have a lead developer / maintainer who largely owns that code whilst being under FD. At the same time the idea would be that that project is consistent with the ethos and approach (and branding) of FD etc.

At same time I don't FD per se is a software hub for "independent developers" to come and just do stuff.

**Comment by roll** [comment]
@rufuspollock 
Probably that's a bad wording from my side and your statement is more correct:

> I think a given project under FD can have a lead developer / maintainer who largely owns that code whilst being under FD. At the same time, the idea would be that that project is consistent with the ethos and approach (and branding) of FD etc.

One thing which I think is crucial - we need an option when this developer/maintainer owns that code without `largely` or other limitations. Meaning that he has the last word on anything related to this project. If FD and this developer run into insoluble disagreement the project can leave the organization.  

> At same time I don't FD per se is a software hub for "independent developers" to come and just do stuff.

Sure, what I meant is more like Apache Incubator (for a subset of projects) - https://incubator.apache.org/

**Comment by rufuspollock** [comment]
> One thing which I think is crucial - we need an option when this developer/maintainer owns that code without largely or other limitations. Meaning that he has the last word on anything related to this project. If FD and this developer run into insoluble disagreement the project can leave the organization.

Yes, i think that generally sounds good - and would flow from your incubator point.

> Sure, what I meant is more like Apache Incubator (for a subset of projects) - https://incubator.apache.org/

@roll love it 😄 👍 👍 

The one point here for me is that (I think) FD should aim to a be more coherent than Apache - not only in how the components fit together but in their look and feel.

**Comment by lwinfree** [comment]
I think the [software page](https://frictionlessdata.io/software/) on the site has achieved this goal.

**Comment by roll** [comment]
@lwinfree 
Also, we might need some kind of public agreement for people moving their projects to FD. I think it can be a part of the government work.
