### ISSUE TITLE
specs url not redirecting

### ISSUE THREAD

**Issue by lwinfree** [frictionlessdata/frictionlessdata.io#486]
The old specs url (frictionlessdata.io/specs) isn't redirecting to the new specs url (https://specs.frictionlessdata.io/). 

We have the old url written in several places from previous work, so it would be good to have it redirect to the new site.

## Tasks

* [ ] fix redirect

**Comment by lauragift21** [comment]
I'll take a look and fix it @lwinfree

**Comment by rufuspollock** [comment]
@lwinfree @lauragift21 this is something for OKF team as this redirect needs to at the cloudflare level - see original issue about this https://github.com/frictionlessdata/project/issues/432

**Comment by lwinfree** [comment]
Hi @amercader could you please look at this when you get a chance?

**Comment by rufuspollock** [comment]
@lwinfree i note that https://frictionlessdata.io/specs/ **is** redirecting but https://frictionlessdata.io/specs (no slash) is **not**. I think @amercader just needs to remove / from his redirection config ...

**Comment by amercader** [comment]
This is now done, frictionlessdata.io/specs redirects correctly

**Comment by lwinfree** [comment]
thanks @amercader!
