### ISSUE TITLE
Guide: Data Flows

### ISSUE THREAD

**Issue by lauragift21** [frictionlessdata/frictionlessdata.io#488]
Write out the section for the guide on Data Flows.

subissue of: #430 

### Content Draft

https://hackmd.io/FYj0J9zRTUmeAM19NqYu1A

## Acceptance

* [ ] we have a working guide for Data Flows

## Tasks

* [ ]  Data Flows
* [ ]  Data Flows Concept
* [ ]  More ....

**Comment by sglavoie** [comment]
**WONTFIX**: Closing because the task list is not detailed enough and there is no sign of activity on this issue in the recent months. Please feel free to re-open with more details.

**Comment by rufuspollock** [comment]
@sglavoie this is indeed part of #430 - i think it is still relevant. But we can think and then reopen if appropriate.
