### ISSUE TITLE
[Misc] Make Website Fully Responsive

### ISSUE THREAD

**Issue by lauragift21** [frictionlessdata/frictionlessdata.io#492]
This issue addresses areas on our website that needs to be improved.

## Acceptance

* [x] The website is fully responsive
## Tasks

* [x] Improve / Fix mobile responsiveness on the website (e.g. footer not fully responsive)

**Comment by rufuspollock** [comment]
@lauragift21 can we get a bit more descriptive heading and can issues start with a description / job story ...

**Comment by rufuspollock** [comment]
@lauragift21 can you update the title for this issue so it accurately reflects the contents. I came and looked at it when i got a notification and could have skipped if notification had been "Make website fully responsive: Fixed"
