### ISSUE TITLE
[epic] Content and Docs Upgrade (Q2 2020)

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/frictionlessdata.io#497]
For background and intro to documentation: https://documentation.divio.com/

## 4 Types of Documentation

* Guide
* Howtos
* Explanation
* Reference

![image](https://user-images.githubusercontent.com/180658/81076328-d332c500-8eeb-11ea-8b3a-d0f4f3d1072d.png)

## Tasks

* [ ] Guide #430 
* [ ] Howtos #495

**Comment by lwinfree** [comment]
closing as this has been implemented via the new framework docs site & the main website update
