### ISSUE TITLE
Remove unnecessary line wrapping in all the specs

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/frictionlessdata.io#503]
The specs e.g. https://specs.frictionlessdata.io/data-package/ seem to have line wrapping that is showing up in the rendered site. 

I suspect source got linewrapped at some point. We don't want this - not only in itself - but because it messes with rendered site e.g.

![image](https://user-images.githubusercontent.com/180658/81990761-14d81400-9640-11ea-9587-89003b2d1b31.png)

This is low priority but a good, simple first issue for someone.

## Acceptance

* [ ] Lines wrap at end of line in rendered pages.

## Tasks

* [ ] ...

**Comment by lwinfree** [comment]
This looks fixed to me.
