### ISSUE TITLE
csvconf blog

### ISSUE THREAD

**Issue by lwinfree** [frictionlessdata/frictionlessdata.io#505]
I think it would be nice to write up a blog about csvconf highlighting the FD talks & relevance.

## Acceptance

* [x]  blog published on site

## Tasks

* [x] @lwinfree to write the blog

## Timeline:
I can work on it over the next few weeks.

**Comment by lwinfree** [comment]
Here is the blog post: https://csvconf.com/going-online We could either post it in its current state, or we could tailor it to be more focused on the FD talks. Thoughts?

**Comment by lauragift21** [comment]
I think this is great @lwinfree! I think it might be best to tailor it to be more focused on the Frictionless Data session that was held.

**Comment by lwinfree** [comment]
fixed
