### ISSUE TITLE
Configurable "banner" at top of screen to highlight special stuff e.g. an upcoming webinar, a new release etc

### ISSUE THREAD

**Issue by monikappv** [frictionlessdata/frictionlessdata.io#514]

**Comment by AngelineRollbar** [comment]
Hi There! The old one is still up and we'll need to change the current one to June 12, 2020 12 PM PDT. to the same link. Is that possible?

**Comment by monikappv** [comment]
@AngelineRollbar hey. I am not sure what you are referring to, can you be a bit more specific?

**Comment by sglavoie** [comment]
**WONTFIX**: Not enough information to work with, the issue has been abandoned for a few months.
