### ISSUE TITLE
Improve CKAN <=> Frictionless conversion (library)

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/frictionlessdata.io#518]
Improve existing converter and especially the docs.

Existing converter: https://github.com/frictionlessdata/frictionless-ckan

~~In the process, also document CKAN metadata and its mapping to Frictionless (even more aside: extract list of Frictionless metadata into a structured format for quick display and searching 😉)~~ MOVED to frictionlessdata/specs#776 

This is now a placeholder and all work has moved to the frictionless-ckan issue https://github.com/frictionlessdata/frictionless-ckan/issues/15

**Comment by sglavoie** [comment]
Update: I have worked on listing the fields for Frictionless Data via script. I have added those in the Google Spreadsheet in the "Frictionless" sheet.

The code I wrote with TDD in mind is located here: https://github.com/sglavoie/fd_metadata

**Comment by sglavoie** [comment]
### Update

* About the task **Mapping of Frictionless <=> CKAN**, I have added as many details as I could to **[the CKAN sheet in the spreadsheet](https://docs.google.com/spreadsheets/d/1XdqGTFni5Jfs8AMbcbfsP7m11h9mOHS0eDtUZtqGVSg/edit#gid=1925460244)**.

* About the task **Write script to auto extract from json schemas to CSV with columns**, I have replied to **[the issue frictionlessdata/project#1 in sglavoie/fd_metadata (_Tidying_)](https://github.com/sglavoie/fd_metadata/issues/1)** and tidied up everything. The results are summarized **[in the comment I left](https://github.com/sglavoie/fd_metadata/issues/1#issuecomment-643353592)** on that same issue.
  * The changes are visible in the repo itself, but for convenience, I have created **[this Gist](https://gist.github.com/sglavoie/133e1560c8d90f4bb7d31ce8de5faf6f)** with the minimum amount of code required to run the script and the tests.

**Comment by rufuspollock** [comment]
FIXED. This happened with extensive improvements in code and docs and v1.0 release of https://github.com/frictionlessdata/frictionless-ckan is out.,
