### ISSUE TITLE
fix underlined styling on FD homepage

### ISSUE THREAD

**Issue by lwinfree** [frictionlessdata/frictionlessdata.io#526]
On the FD website homepage, the words "Researchers", "Data Scientists" and "Data Engineers": they are underlined when hovering them (same for "Sourcing Data", etc.). Carles said: "I automatically thought that they might be a link :slight_smile: then realised that no... should they get underlined for the web style? or is a "bug"?"

I'm guessing this is a styling issue with the h3 class?

Tagging @monikappv for help please :-)

**Comment by monikappv** [comment]
not sure why these were underlined on hover. however, problem solved. :) 

FIXED.
