### ISSUE TITLE
Documentation structure

### ISSUE THREAD

**Issue by roll** [frictionlessdata/frictionlessdata.io#527]
I want to share my vision of how the documentation on the main can look like. I'm only talking about two first sections:
- Learn
- Tooling

## Current

I think the main problem here that it just lists our technologies when coming users don't really care about it. They usually come to solve their problems or to find solutions applicable to their platform. I would bet that they don't really care about e.g. `tabulator` :see_no_evil: 

- Learn
  - Guide
  - How-to-guide
  - Table Schema
  - Data Package
- Tooling
  - Table Schema Tools
  - Data Package Tools
  - Tabulator
  - Goodtables
  - Data Package Pipelines
  - Datahub
  - Labs

## Idea

To rebase on a platform-based approach and provide proper project overview in the introduction. We also can re-use all the documentation written for the `frictionless` libraries.

- Introduction (maybe having here only one article that gives the full overview of the project and problems it solves - we can consider it as a project's map)
- Tooling
  - FD in Visual UI (for now, we can list current UI apps)
  - FD in Python (the source code can live in the library repository)
    - Introductory Guide
    - Advanced Guide
    - How-to-guides
    - API reference
    - etc
  - FD in R-Lang (the source code can live in the library repository)
    - whatever docs are written for R
  - FD for other platforms
  - other stuff like Datahub/Labs (or maybe it can another top-level section like products)

---

Please preserve this line to notify @rufuspollock  @lwinfree (lead of this repository)

**Comment by lwinfree** [comment]
tagging @Irio to think about this too :-)

**Comment by roll** [comment]
There are few guides that I think can be used on the main site's Python section after some refining and editing:
- [Introductory Guide](https://github.com/frictionlessdata/frictionless-py/blob/master/docs/introductory-guide.md#introductory-guide)
- [Describing Data](https://github.com/frictionlessdata/frictionless-py/blob/master/docs/describing-data.md#describing-data) (that's basically an introduction into FD specs)

And more guides are coming :+1:

**Comment by lwinfree** [comment]
@roll I think this has been done now - are you OK if I close this issue?

**Comment by roll** [comment]
@lwinfree 
Sure
