### ISSUE TITLE
Improving website navigation

### ISSUE THREAD

**Issue by roll** [frictionlessdata/frictionlessdata.io#528]
Initially, I was proposing Docosaurus 2 as a website engine and one of the main features of this project was its awesome navigation. For example, for a random article, it completely presents your current location visually and gives a lot of option for the following reading (prev/next/toc/articles/etc) :

![navigation-modern](https://user-images.githubusercontent.com/557395/89297630-dcf3d200-d66c-11ea-945d-7861ca9668ec.png)

What we have now I'd say we are missing a great deal of this functionality. Consider some random page you were given a link for. You basically cannot say where you are, what to read next etc:

![navigation-current](https://user-images.githubusercontent.com/557395/89297813-280de500-d66d-11ea-8957-0493f1f4d809.png)

I think navigation is as important as contents and we really need to focus on it either.
 
cc @lwinfree @rufuspollock @sglavoie

**Comment by lwinfree** [comment]
Those are good points Evgeny. So, currently we have a navigation menu showing the headers within a page, but I agree that we could add in some additional pointers to list the other docs too.

**Comment by lwinfree** [comment]
hey @roll to restart this convo... we want:
- the tooling section should have 1 sidebar that lists *all* of the pages (children)
- each page should have this same sidebar, and should show which page you are on
- at the bottom of each page, there should be 2 buttons showing the previous topic/page and the next topic/page

of note: some pages (like this one https://frictionlessdata.io/tooling/python/api-reference/) either need to be rewritten to not use h3s, or we need to change the sidebar so we aren't displaying every single thing (that's my opinion - open to others)

Does that sound like a good start to you? Am I missing something?

**Comment by roll** [comment]
@lwinfree 
I think the best summary of my vision is the initial screenshot - 2 sidebars + prev/next buttons + top menu indication 

Regarding the API Reference and similar documents, I would not really be worried about ATM how it looks as it's very low-level and the main purpose of having it is to have an ability to link to sections like - https://frictionlessdata.io/tooling/python/api-reference/#textloader. No one will be reading it from top to bottom (we can disable the sections menu for such documents if needed etc)

**Comment by roll** [comment]
DONE in https://github.com/frictionlessdata/website/issues/177
