### ISSUE TITLE
Announcing frictionless-py

### ISSUE THREAD

**Issue by roll** [frictionlessdata/frictionlessdata.io#529]
We're happy to announce that `frictionless-py` has just been released for initial testing and feedback collection. To test it please follow the link below:

# [Frictionless for Python (frictionless-py)](https://github.com/frictionlessdata/frictionless-py)

It's a high-level framework that was created to simplify overall user-experience for working with Frictionless Data in Python. It provides a lot of high-level improvements in addition to many low-level fixes. This software and its documentation are in a beta-testing stage so some bugs can occur and there are still a lot of typos and holes in the docs. For reading documentation you can use Table of Contents on the left of Google Colab interface or open a markdown version if you follow the github link above (the links at the bottom of the readme).

## Documentation

- [Getting Started](https://colab.research.google.com/drive/1VyDx6C3pxF3Vab8MxH_sI86OTSNmYuDJ)
- [Introduction Guide](https://colab.research.google.com/drive/1HGXJa7BWyEgoGZLkC6tKt2DMqgeHibEY)
- [Describing Data](https://colab.research.google.com/drive/1eIq1ZTUntJplRxkGHxmqlxZ0zyXCm0wU)
- [Extracting Data](https://colab.research.google.com/drive/1is_PcpzFl42aWI2B2tHaBGj3jxsKZ_eZ)
- [Validating Data](https://colab.research.google.com/drive/1cJSZlG_v6OI3I2FtnXdKOSPjhwZNjMK1)
- [Transforming Data](https://colab.research.google.com/drive/1C4dFWDExyxzGIwLUovrDQZghZK4JK2PD)
- --
- [RFC6: Software Structure](https://github.com/frictionlessdata/project/blob/master/rfcs/0006-software-structure.md)

**Comment by rufuspollock** [comment]
@roll this was great. Can we get the plan / summary we wrote into RFC 6 and the key agreements there.

**Comment by roll** [comment]
Sure. I'll add

**Comment by roll** [comment]
The announcement is done now.

We're working on the first stable version - https://github.com/frictionlessdata/project/issues/543
