### ISSUE TITLE
CSV Data type validation

### ISSUE THREAD

**Issue by metabsd** [frictionlessdata/frictionlessdata.io#530]
This is more a question than an Issue.

This is a CSV example : https://gist.github.com/metabsd/a78f5048ad09abf76e6fa5ef94fa8b63

Can I validate the port data to be only those three example. With pattern matching or something else.

Thx!

---

Please preserve this line to notify @lwinfree (lead of this repository)

**Comment by lwinfree** [comment]
CC @roll this is a continuation of metabsd's question from Discord. Can you help answer plz?

**Comment by roll** [comment]
Hi @metabsd 

You can use a schema's pattern constraint:

```python
from pprint import pprint
from frictionless import validate

source = 'https://gist.githubusercontent.com/metabsd/a78f5048ad09abf76e6fa5ef94fa8b63/raw/5d9532efd5eda6796bff92f3f4740e00e13fc79a/gistfile1.txt'
report = validate(source, format='csv', patch_schema={'fields': {'port': {'constraints': {'pattern': '^9091'}}}})
pprint(report.flatten(['code', 'message']))
# [['constraint-error',
#  'The cell "12000:14000" in row at position "2" and field "port" at position '
#  '"8" does not conform to a constraint: constraint "pattern" is "^9091"'],
# ['constraint-error',
#  'The cell "9092,2181,9093,27017:27027" in row at position "4" and field '
#  '"port" at position "8" does not conform to a constraint: constraint '
#  '"pattern" is "^9091"']]
```

**Comment by metabsd** [comment]
Thank a lot!!! Now I have to find the right regex :) This is really nice. Good work!!!

**Comment by roll** [comment]
Great. Thanks!

**Comment by metabsd** [comment]
There a way that I can specify a custom message when Pattern don't match ? Thx!

**Comment by roll** [comment]
What kind of interface do you use: Python, CLI?

If it's Python you can just modify the report.

**Comment by metabsd** [comment]
Yes I'm using the CLI. I'm using frictionless inside an Ansible Playbook to validate couple csv. I would like to be able to add an option in the YAML resource file where I can define the schema to choose the message. If it's not possible I will write a custom module with frictionless library to overwrite the report. Thx!

**Comment by roll** [comment]
Yea I think that updating the report is the way to go atm.
