### ISSUE TITLE
Set https only for frictionlessdata.io

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/frictionlessdata.io#533]
We want frictionlessdata.io to be https only (and it isn't atm http works for sub pages e.g. http://frictionlessdata.io/table-schema/). Note that root domain does redirect so suspect page rules are misconfigured.

## Acceptance

* [x] http://frictionlessdata.io/table-schema/ and any other pages redirect to https versions

## Tasks

* [x] Login to cloudflare and turn on https only (which will auto redirect http to https) (remove page rule for this)

/cc @lwinfree

**Comment by lwinfree** [comment]
sounds good to me @rufuspollock. @amercader do you have access to cloudflare & if so, can you please do this? Thanks!

**Comment by amercader** [comment]
This is now done @lwinfree
