### ISSUE TITLE
Recording mentions and uses of Frictionless tooling

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/frictionlessdata.io#538]
When I see a reference or use of Frictionless tooling online I want to record it so that we have a set of referenceable examples of people using it that we can cite to funders or mention on our website

## Acceptance

* [ ] ...

## Tasks

* [ ] ...

## Analysis

* online article using table schema … https://hackersandslackers.com/infer-datatypes-from-csvs-to-create/

**Comment by lwinfree** [comment]
at OKF, we've created a google form/spreadsheet combo to track things like this. Just FYI in case that is a helpful example to think about :-)

**Comment by rufuspollock** [comment]
@lwinfree great, is it public and can I add items to it?

**Comment by lwinfree** [comment]
@rufuspollock it (the OKF one I mean) isn't for general FD items. I brought it up as a suggestion for how we/you might want to start keeping track of general FD items

**Comment by rufuspollock** [comment]
@lwinfree great suggestion - so you mean we could create a spreadsheet like that? 😄 👍

**Comment by lwinfree** [comment]
yes :-)

**Comment by lwinfree** [comment]
@sapetti9 We haven't used the OKF sheet in a while...what do you think about re-vamping it?

**Comment by sapetti9** [comment]
First draft created: https://forms.gle/hBJhpwY2TdPEFpc97
