### ISSUE TITLE
Implement frictionless-js library

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/frictionlessdata.io#541]
We want a JS toolkit following our RFC 006 https://github.com/frictionlessdata/project/blob/master/rfcs/0006-software-structure.md

We already have a base library in the form https://github.com/datopian/data.js which we can migrate over.

Then we need to add more functionality - a lot of this is in https://github.com/datopian/data-cli e.g. we have "show" (`cat` and `info`), `validate`, `init`... 

## Tasks

* [x] Migrate Datopian's data.js to become basis of frictionless-js https://github.com/frictionlessdata/frictionless-js/issues/85 **DONE**
* [ ] Migrate https://github.com/datopian/data-cli into

## Qus

* Should we actually have data.js as frictionless-sdk-js? and have https://github.com/datopian/data-cli become frictionless-js (latter has more stars and is actually more related).
  * Pros: clean separation, keep base library simple
  * Cons: we have two libs with some potential confusion

**Comment by sglavoie** [comment]
**WONTFIX**: Closing because there is no action to be taken.

**Comment by rufuspollock** [comment]
@sglavoie i opened this as a placeholder today because we specifically discussed this as something we are working on. Reopening.

**Comment by roll** [comment]
Hi, do we have more specific goals like releasing _some_ version having _some_ functionality? Probably that what you're planning to add to the acceptance so just curious as it's empty yet

**Comment by rufuspollock** [comment]
@roll we already have the basic version done - see the repo - as we migrated data.js over last week. I've just updated the description with more info. Note that most of the functionality already existed in `data.js` and `data-cli` - it's a question of moving it over.

**Comment by roll** [comment]
Shall we close it and track further development on the corresponding issue tracker?

**Comment by roll** [comment]
https://github.com/frictionlessdata/frictionless-js
