### ISSUE TITLE
Tool takes CSV, Table schema, and creates a JSON consistent with the schema?

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/frictionlessdata.io#553]
@aborruso asked:

Hi, is there a frictionless data tools - that starting from a csv file and a schema file in which  I set that a specific field is text- that is able to create a json file output, in which an input value of "0123" will be in the JSON something like "fieldName":"0123"?

I'm asking it, because a lot of utilities  return often wrong output results as "fieldName":0123 or "fieldName":123.0 .

I'm looking for a tool that starting from a CSV and schema file, creates a right JSON version of the input.

```
toolx my.csv --schema tableschema.json --output json

{  "fieldname": "0123" }
```

**Comment by lwinfree** [comment]
Hi @aborruso! Apologies for just now responding to this! Does the `schema.to_json` option in Framework solve your issue (e.g. https://framework.frictionlessdata.io/docs/guides/describing-data#describing-a-schema)?

**Comment by aborruso** [comment]
> Hi @aborruso! Apologies for just now responding to this! Does the `schema.to_json` option in Framework solve your issue (e.g. https://framework.frictionlessdata.io/docs/guides/describing-data#describing-a-schema)?

My question is different: I do not want to convert the description file, but to have an output consistent with its description.

I have tested now using `extract` and it works. But I'm opening a new issue related to [this](https://github.com/frictionlessdata/project/discussions/715#discussioncomment-2412867=).

You can close this, thank you

**Comment by aborruso** [comment]
> But I'm opening a new issue related to [this](https://github.com/frictionlessdata/project/discussions/715#discussioncomment-2412867=).

The issue is this one frictionlessdata/frictionless-py#1009
