### ISSUE TITLE
Forum section on website powered off github issues (this repo!)

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/frictionlessdata.io#554]
Could we ~~hack~~ use a github issues based comment system e.g. https://utteranc.es/ (2.3k*)  or https://ocs.now.sh/ (218*) or vssue (337⭐) https://vssue.js.org/ 

Couldn't find any immediate app that did this as forum itself.

**Comment by lwinfree** [comment]
closing as we now use github discussions
