### ISSUE TITLE
CSV in Markdown

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/frictionlessdata.io#555]
This is a topic about using CSV in markdown. (cf also DataDown frictionlessdata/forum#7)

````
```csv
A,B,C
1,2,3
```
````

Would render as:

A | B | C
--|--|--|

## Job Stories

When I am writing markdown and want to have a table (esp data type table) I want to be able to make it quickly and easily 

* Current markdown table syntax is cumbersome (and error prone) esp for small "data" type tables

When I am documenting a data project or dataset I want to include data snippets (already in CSV) quickly and easily so that people can understand my dataset better

* Already have data in csv so don't want to have to convert

## MVP

An MVP here would be e.g. a markdown-it plugin that support fenced code blocks with type `csv`

## Tasks

* [ ] Research markdown it plugins
  * See https://github.com/markdown-it/markdown-it/tree/master/docs
* [ ] Implement it
* [ ] Try it out e.g. on fd new website

## References

* Discussion in 2016 on pandoc list about pandoc support for CSV sections (either included files or fenced blocks) https://groups.google.com/forum/#!topic/pandoc-discuss/znGQ62WpWrg - started by @mfenner
* marked has support for including CSV files https://marked2app.com/help/Creating_Tables_using_CSV_files.html

**Comment by lwinfree** [comment]
Closing as this is out-of-scope for the frictionless technical roadmap right now.
