### ISSUE TITLE
DataDown - data snippets / files / datasets in markdown

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/frictionlessdata.io#558]
I've had the idea of DataDown for years but never written it up!

"DataDown": having a syntax (based on e.g. Data Resource and/or Data Packages) for including data resources / datasets *in* markdown (you could also reuse as entire file cf formatting for pages for static site generators where you have frontmatter and body - this is almost a separate idea)

````
```data
title: Cases of Coronarvius
format: csv
---
A,B,C
1,2,3
```
````

This should render as a nice mini data file with a table of the data.

Key points:

* "Frontmatter" keys based on FD specs e.g. (Tabular) Data Resource
* Data is inlined after a separator `---` (could also support explicit key like `data` as in Data Resource spec
* Option: could allow for block key to be more explicit e.g. `dataset` or `dataresource` rather than just `data`

## Job Stories

When writing READMEs for datasets or data projects in markdown I want to include info about a data file or a data file snippet so that the reader knows what i'm talking about

When talking / document a dataset I want to show information about the fields / columns so that users know what they are and their means

* In particular, I would like to document fields/columns and have them show up like we have on datahub datasets https://datahub.io/core/pharmaceutical-drug-spending#resource-data
* If i already have this in a data resource or data package I would like to not have to repeat myself

![image](https://user-images.githubusercontent.com/180658/76058079-b3c6fc80-5f7b-11ea-99c6-078f2cabc84a.png)

When I (Rufus) create mini collections of datasets e.g. https://datahub.io/collections I want to include snippets or summaries of data files / datasets (in markdown) so that the reader immediately knows about the data without having to click through to somewhere else

## References

* Frictionless Specs https://specs.frictionlessdata.io/
* VisDown https://visdown.com/

**Comment by domoritz** [comment]
I just got the notification 😇. I think it's better to separate metadata from data because that way you can parse the metadata and the data independently. Assuming that there are n metadata formats and m data formats, you would need n+m parsers if you keep data and metadata separately and m*n parsers if you combine them.

I think this is even true if you just pass of the data to another parser since many parsers rely on having access to the raw file pointer.

**Comment by roll** [comment]
I created a project called **Livemark** with similar scope (and partially based on ideas from CSV in Markdown, VisDown, etc) - https://frictionlessdata.github.io/livemark/

**Comment by lwinfree** [comment]
I'm going to close this since Livemark is serving the same purpose. Please re-open if you think there is more/different work to be done here!
