### ISSUE TITLE
Integration with Zenodo

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/frictionlessdata.io#561]
@pdurbin wrote (Feb 12 on gitter)

> @lwinfree (and others), hi! Great talk at https://fosdem.org/2020/schedule/event/open_research_frictionless_data/ ! I believe you mentioned an integration with Zenodo but I'm having trouble finding any information about this. Can someone please drop a link in here?

@lwinfree wrote

> Hi @pdurbin! For Zenodo, I was refering to our recent Pilot collaboration with Catalyst Co-op, where they packaged US energy data into datapackages & then uploaded to Zenodo. I think this issue is the best place to read a summary: catalyst-cooperative/pudl#425
>
> See also: https://github.com/catalyst-cooperative/pudl/blob/master/src/pudl/load/metadata.py & https://github.com/catalyst-cooperative/pudl/blob/master/docs/datapackages.rst for more info. Let me know if you have other questions, or if you’d like to talk to the Catalyst team!

**Comment by lwinfree** [comment]
closing as this content is captured in various blogs (https://frictionlessdata.io/tag/pilot/)
