### ISSUE TITLE
Frictionless Enhancement Proposals (FEPs) aka Frictionless RFCs

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/frictionlessdata.io#563]
Stuff like Table Schema Catalog in frictionlessdata/forum#5 is a suggestion for a substantial improvement to FD. Github issues (and their threads) are ok but for complex and/or substantial items they can get confusing => could trial having small docs in the form of "Frictionless enhancement proposals"

**Comment by roll** [comment]
@lwinfree 
Shall it be closed as we have the RFC system - https://github.com/frictionlessdata/project/tree/main/rfcs

**Comment by rufuspollock** [comment]
FIXED. As @roll notes we have the RFCs and the process https://github.com/frictionlessdata/project/tree/main/rfcs
