### ISSUE TITLE
website: a page that explains what a datapackage is

### ISSUE THREAD

**Issue by chris48s** [frictionlessdata/frictionlessdata.io#619]
There used to be a really useful page on the website that explains what a datapackage is:
https://web.archive.org/web/20201116202829/https://frictionlessdata.io/data-package/
This has been removed.

Also the "read more" link under Data Package on frictionlessdata.io is dead:

![GIFrecord_2021-03-13_205929](https://user-images.githubusercontent.com/6025893/111044296-84c15180-843f-11eb-8056-de903f94b036.gif)

For the moment I'm linking to https://specs.frictionlessdata.io/data-package/ but the spec isn't a great first explanation of a data package for someone who isn't already familiar with it.

It would be useful if this content could be replaced.

---

Please preserve this line to notify @lwinfree (lead of this repository)

**Comment by rufuspollock** [comment]
@chris48s very good point. I'm having a look.

Aside: @roll through checking the commits to see what happened and wdyt then when we remove urls we add redirects e.g. in https://github.com/frictionlessdata/website/commit/61893a7a824e551ad54dccd53395ab012e162d9c we removed some urls and we could redirect to the replacement content e.g. /tooling/python => to /tooling/framework/ (if that is the appropriate redirect)

**Comment by rufuspollock** [comment]
@chris48s ok found where it happened: https://github.com/frictionlessdata/website/commit/b5c851a35105c49aa1b3d7463a1b05fc4dd499ce

Can put this back now ...

**Comment by rufuspollock** [comment]
FIXED in https://github.com/frictionlessdata/website/commit/996ed1c01b44467706ba1b347101d3d8d89c269a

**Comment by roll** [comment]
Thanks @rufuspollock

**Comment by roll** [comment]
BTW @sglavoie, I didn't understand how to deploy the website when I was updating the Python docs link. Is it enough just to push to master?

**Comment by sglavoie** [comment]
@roll Yes, we just need to push to `master` thanks to the workflow set up with GitHub Actions, which does the following:

* https://github.com/frictionlessdata/website/blob/ab428c1c178cf8c65e31cd7ad1ab972fad8f8f8f/.github/workflows/main.yml#L2 executes on each push;
* https://github.com/frictionlessdata/website/blob/ab428c1c178cf8c65e31cd7ad1ab972fad8f8f8f/.github/workflows/main.yml#L13 starts a job to deploy;
  * https://github.com/frictionlessdata/website/blob/ab428c1c178cf8c65e31cd7ad1ab972fad8f8f8f/.github/workflows/main.yml#L23 the website will be checked out, installed and built by that point;
  * https://github.com/frictionlessdata/website/blob/ab428c1c178cf8c65e31cd7ad1ab972fad8f8f8f/.github/workflows/main.yml#L25 and here it's deployed to GitHub Pages.

Hope that's useful! :smiley:
