### ISSUE TITLE
Make code citable?

### ISSUE THREAD

**Issue by georgeslabreche** [frictionlessdata/frictionlessdata.io#628]
# Overview

Make all frictionlessdata repos citable with a DOI via Zenodo:
https://guides.github.com/activities/citable-code/

---

Please preserve this line to notify @iSnow (lead of this repository)

**Comment by roll** [comment]
I've moved the issue the project issue tracker :+1:

**Comment by lwinfree** [comment]
OK this is now set up for frictionless-py & the project repo. When the next release is done for each of those repos, they will have a DOI minted! I'm closing now as this will happen automatically at the next release. Thanks for the idea!
