### ISSUE TITLE
GeoJSON data package example

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/frictionlessdata.io#64]
This is very straightforward but would be nice to provide a proper example.

Would be nice to use some real world data - where doe we get example data from?
- https://github.com/john-sandall/geocouncil
- crime data
- AfTerFibre e.g. https://github.com/stevesong/afterfibre-kml/blob/master/Kenya/KDN/KDN.geojson

Suggest we want, several examples:
- [x] local data "in the repo"
- [ ] "remote" data (like we did with topojson)
- [ ] <del>[optional] "inline data" - this would be kind of cute but is not essential</del>

Would probably push these to ex-{pkgname} in https://github.com/datasets as per  https://github.com/datasets/ex-topojson

**Comment by sabas** [comment]
What about converting NaturalEarthData (http://www.naturalearthdata.com/downloads/ ), for example country borders?
Topojson example https://github.com/sabas/sabas.github.io/blob/master/topojson/naturalearth_countries.topojson

**Comment by rgrp** [comment]
@sabas this would be great - I would actually suggest taking a look / adding issues to the core datasets registry https://github.com/datasets/registry/issues as natural earth stuff should probably go in there.
