### ISSUE TITLE
Frictionless <> Flat Data integration

### ISSUE THREAD

**Issue by roll** [frictionlessdata/frictionlessdata.io#681]
@amercader's idea to integrate Flat Data - https://octo.github.com/projects/flat-data - with the Frictionless Github Action is really promising :+1:

We need some real word data example that fetches/visualize data using Flat Data and uses Frictionless Repository to validate the data in between

---

Please preserve this line to notify @lwinfree (lead of this repository)

**Comment by aborruso** [comment]
It was also an idea of mine 🙃

**Comment by roll** [comment]
@aborruso :smile: :+1:

**Comment by roll** [comment]
We've ended up with Livemark pursuing this goal - https://livemark.frictionlessdata.io/
