### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by peterdesmet** [frictionlessdata/frictionlessdata.io#683]
The link https://frictionlessdata.io/data-package/ used to work. It now redirects to https://frictionlessdata.io/about/introduction/ which is a 404.

---

Please preserve this line to notify @lwinfree (lead of this repository)

**Comment by lwinfree** [comment]
thanks @peterdesmet I'm actually fixing that in a PR today! :-) Please let me know if you catch other 404s in the future.

**Comment by lwinfree** [comment]
closed via https://github.com/frictionlessdata/website/pull/201
