### ISSUE TITLE
Onboarding Shashi

### ISSUE THREAD

**Issue by lwinfree** [frictionlessdata/frictionlessdata.io#717]
Welcome Shashi!

## To Do's
* [x] (Lilly) finish drafting onboarding doc
* [x] (Evgeny) Review technical roadmap
* [x] (Edgar) Review technical roadmap
* [x] (Adria) review all of the doc
* [x] (Shashi) read the onboarding doc
* [x] (Shashi) close this issue when you are done reading the onboarding doc

**Comment by shashigharti** [comment]
Completed
