### ISSUE TITLE
Workshop at TU Delft

### ISSUE THREAD

**Issue by lwinfree** [frictionlessdata/frictionlessdata.io#718]
## Abstract
This workshop training will teach researchers about reproducible data workflows, including how to make tabular data more FAIR and of higher quality. The lesson will be part-lecture, and mostly hands-on Python coding in a notebook, with technical helpers available to help. Participants will learn how to use the Python Frictionless Framework (https://framework.frictionlessdata.io/) to create and edit metadata and schemas, how to validate their data, and how to write a pipeline to prepare data for publication within the TU Delft Library repository. This hands-on workshop will occur over 2 half-day sessions.

## Details
April 28 & 29
Registration TBA

**Comment by lwinfree** [comment]
## To Do's
- [x] jupyter notebook
- [x] host helpers session
- [x] present at workshop
- [x] write blog post/comms about the event

**Comment by augusto-herrmann** [comment]
Thats great, @lwinfree! How was the workshop?

**Comment by lwinfree** [comment]
Hi @augusto-herrmann ! It was good! The participants seemed engaged & like they learned! We'll be writing a blog summary in the coming weeks :-)

**Comment by lwinfree** [comment]
(tagging @sapetti9 - I can start a blog draft when we are back from the F2F, and maybe you can help write/edit? 😄 )

**Comment by lwinfree** [comment]
DONE!

blog: https://frictionlessdata.io/blog/2022/05/24/_2022-0524-tu-delft-training/

**Comment by augusto-herrmann** [comment]
Awesome! Thanks for sharing, @lwinfree.
