### ISSUE TITLE
add frictionless-r to code contributors page

### ISSUE THREAD

**Issue by sapetti9** [frictionlessdata/frictionlessdata.io#803]
# Overview

 We should add frictionless-r (https://github.com/frictionlessdata/frictionless-r) to https://frictionlessdata.io/people/#code-contributors.

**Comment by roll** [comment]
@sapetti9 
@peterdesmet 
In general, what do you think of maybe creating a subdomain for the R framework like `r(lang).frictionlessdata.io`?

**Comment by peterdesmet** [comment]
For me there is no need for an `r.frictionlessdata.io` domain. The `frictionless` R package I maintain is part of rOpenSci, a collective of curated/reviewed R packages. It has its documentation there https://docs.ropensci.org/frictionless/

I can't speak for the two object oriented R packages https://github.com/frictionlessdata/datapackage-r and https://github.com/frictionlessdata/tableschema-r
